project_id = "mkzblwlxkjhsbkvwkdyn"

[functions.track-device]
verify_jwt = true

[functions.create-client]
verify_jwt = true

[functions.send-credentials]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.risepay-webhook]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.analyze-food]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = true

[functions.create-client-complete]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false