project_id = "mkzblwlxkjhsbkvwkdyn"

[functions.track-device]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.send-credentials]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.risepay-webhook]
verify_jwt = false

[functions.analyze-food]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = true